# NumPy.

Імпортуйте numpy.

In [2]:
import numpy as np

##### Створіть масив з 10 нулів:

In [3]:
# Створення списку чисел
numbers = [0, 1, 4]

# Перетворення списку у numpy масив
num = np.array(numbers)

# Повторення кожного елемента масиву 10 разів
for i, _ in enumerate(range(len(num))):
    print(np.repeat(num[i], 10))


[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[4 4 4 4 4 4 4 4 4 4]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### Створіть масив з 10 одиниць:

In [4]:
# ваш код тут

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Створіть масив з 10 четвірок:

In [6]:
# ваш код тут

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

##### Створіть масив з цілими числами у проміжку від 15 до 30:

In [5]:
np.arange(15, 31)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

##### Створіть масив з непарних чисел у межах від 15 до 30:

In [6]:
np.arange(15, 31, 2)

array([15, 17, 19, 21, 23, 25, 27, 29])

array([15, 17, 19, 21, 23, 25, 27, 29])

##### Створіть матрицю 10 на 10, де числа будуть від 1 до 100:

In [9]:
np.arange(1, 101).reshape(10, 10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

##### Згенеруйте матрицю, як у прикладі:

In [11]:
matrix = np.linspace(0.01, 1.0, 100).reshape(10, 10)

print(matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

##### Створіть діагональну матрицю 5 на 5:

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### Згенеруйте випадкове число використовуючи NumPy:

In [14]:
np.random.seed(100) # цей метод доданий, щоб числа, згенеровані випадково були однакові після декількох запусків

np.random.rand()


0.5434049417909654

0.5434049417909654

##### Згенеруйте масив з 25 випадкових чисел:

In [15]:
np.random.rand(25)

array([0.27836939, 0.42451759, 0.84477613, 0.00471886, 0.12156912,
       0.67074908, 0.82585276, 0.13670659, 0.57509333, 0.89132195,
       0.20920212, 0.18532822, 0.10837689, 0.21969749, 0.97862378,
       0.81168315, 0.17194101, 0.81622475, 0.27407375, 0.43170418,
       0.94002982, 0.81764938, 0.33611195, 0.17541045, 0.37283205])

array([0.27836939, 0.42451759, 0.84477613, 0.00471886, 0.12156912,
       0.67074908, 0.82585276, 0.13670659, 0.57509333, 0.89132195,
       0.20920212, 0.18532822, 0.10837689, 0.21969749, 0.97862378,
       0.81168315, 0.17194101, 0.81622475, 0.27407375, 0.43170418,
       0.94002982, 0.81764938, 0.33611195, 0.17541045, 0.37283205])

##### Створіть масив, у якому 20 чисел лінійно розташовані у проміжку від 0 до 1:

In [16]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Індексування.
Необхідно написати код, щоб отримати такі самі дані, як у прикладах з наперед заданої матриці.

In [23]:
matrix = np.arange(0, 25).reshape(5,5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [22]:
print(matrix[0:2, 3:5])

[[3 4]
 [8 9]]


array([[3, 4],
       [8, 9]])

In [25]:
print(matrix[2, 2])

12


12

In [26]:
matrix[2]

array([10, 11, 12, 13, 14])

array([10, 11, 12, 13, 14])

## Робота з бібліотекою Pandas.

Імпортуйте pandas.

In [4]:
import pandas as pd

    ### Завантаження даних у DataFrame.

In [28]:
df = pd.read_csv('data.csv')

Виведіть перші 10 рядочків з DataFrame.

In [29]:
df.head(10)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0    8/23/2012  199697               1               1         Brazil   
1     9/7/2016  188693               2               1            NaN   
2    6/24/2013  160026               3               1            NaN   
3    8/24/2015  119109               4               4      Lithuania   
4    4/20/2014  118149               5               5         Canada   
5   11/13/2012  116060               6               4  United States   
6    2/28/2014  114214               7               3          China   
7    11/8/2015  106314               8               8         Russia   
8    6/25/2010  103017               9               6        Austria   
9    7/20/2016  102460              10               9         Latvia   

       Continent  
0  South America  
1            NaN  
2            NaN  
3         Europe  
4  North America  
5  North America  
6           Asia  
7           Asia  
8         Europe  
9         Europe

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0    8/23/2012  199697               1               1         Brazil   
1     9/7/2016  188693               2               1           None   
2    6/24/2013  160026               3               1           None   
3    8/24/2015  119109               4               4      Lithuania   
4    4/20/2014  118149               5               5         Canada   
5   11/13/2012  116060               6               4  United States   
6    2/28/2014  114214               7               3          China   
7    11/8/2015  106314               8               8         Russia   
8    6/25/2010  103017               9               6        Austria   
9    7/20/2016  102460              10               9         Latvia   

       Continent  
0  South America  
1           None  
2           None  
3         Europe  
4  North America  
5  North America  
6           Asia  
7           Asia  
8         Europe  
9         Europe

Виведіть останні 10 рядочків з DataFrame.

In [30]:
df.tail(10)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
4757    8/29/2010      20            4757              73       Colombia   
4758   11/11/2010      19            4758             117            NaN   
4759   11/24/2011      18            4759            1081            NaN   
4760   11/15/2010      16            4760             151         Israel   
4761    1/17/2012      16            4761            1201  United States   
4762   11/24/2010      14            4762             265        Belgium   
4763     1/1/2012      14            4763            1444            NaN   
4764     1/9/2012      14            4764            1444          India   
4765    1/15/2012      14            4765            1444            NaN   
4766    1/17/2012      14            4766            1444            NaN   

          Continent  
4757  South America  
4758            NaN  
4759            NaN  
4760           Asia  
4761  North America  
4762         Europe  
4763            NaN  
4764           Asia  
4765            NaN  
4766            NaN

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
4757    8/29/2010      20            4757              73       Colombia   
4758   11/11/2010      19            4758             117           None   
4759   11/24/2011      18            4759            1081           None   
4760   11/15/2010      16            4760             151         Israel   
4761    1/17/2012      16            4761            1201  United States   
4762   11/24/2010      14            4762             265        Belgium   
4763     1/1/2012      14            4763            1444           None   
4764     1/9/2012      14            4764            1444          India   
4765    1/15/2012      14            4765            1444           None   
4766    1/17/2012      14            4766            1444           None   

          Continent  
4757  South America  
4758           None  
4759           None  
4760           Asia  
4761  North America  
4762         Europe  
4763           None  
4764           Asia  
4765           None  
4766           None

Виведіть випадкові 10 рядочків з DataFrame.

In [33]:
df.sample(10)

RegisterDate  Points  CurrentRanking  HighestRanking         Country  \
1440    6/14/2016    4623            1440            1024     South Korea   
211      6/1/2017   23359             212             171             NaN   
1350    7/28/2016    4883            1350             945             NaN   
2729    10/4/2016    1850            2729            2683   United States   
3535   11/19/2014     852            3535            1405  Czech Republic   
2152   11/25/2012    2780            2152            1153  United Kingdom   
1054    3/18/2011    6393            1054              40          France   
4641    5/11/2012     104            4641            1273             NaN   
134     12/3/2015   31905             135             120           Spain   
3530    12/9/2013     857            3530            2173             NaN   

          Continent  
1440           Asia  
211             NaN  
1350            NaN  
2729  North America  
3535         Europe  
2152         Europe  
1054         Europe  
4641            NaN  
134          Europe  
3530            NaN

RegisterDate  Points  CurrentRanking  HighestRanking         Country  \
1440    6/14/2016    4623            1440            1024     South Korea   
211      6/1/2017   23359             212             171            None   
1350    7/28/2016    4883            1350             945            None   
2729    10/4/2016    1850            2729            2683   United States   
3535   11/19/2014     852            3535            1405  Czech Republic   
2152   11/25/2012    2780            2152            1153  United Kingdom   
1054    3/18/2011    6393            1054              40          France   
4641    5/11/2012     104            4641            1273            None   
134     12/3/2015   31905             135             120           Spain   
3530    12/9/2013     857            3530            2173            None   

          Continent  
1440           Asia  
211            None  
1350           None  
2729  North America  
3535         Europe  
2152         Europe  
1054         Europe  
4641           None  
134          Europe  
3530           None

Виведіть розмірність DataFrame.

In [34]:
df.shape

(4767, 6)

(4767, 6)

Виведіть назви колонок DataFrame.

In [38]:
df.columns

Index(['RegisterDate', 'Points', 'CurrentRanking', 'HighestRanking', 'Country',
       'Continent'],
      dtype='object')

Index(['RegisterDate', 'Points', 'CurrentRanking', 'HighestRanking', 'Country',
       'Continent'],
      dtype='object')

Виведіть інформацію про колонку індексів DataFrame.

In [39]:
df.index

RangeIndex(start=0, stop=4767, step=1)

RangeIndex(start=0, stop=4767, step=1)

Виведіть інформацію про типи даних елементів у DataFrame.

In [40]:
df.dtypes

RegisterDate      object
Points             int64
CurrentRanking     int64
HighestRanking     int64
Country           object
Continent         object
dtype: object

RegisterDate      object
Points             int64
CurrentRanking     int64
HighestRanking     int64
Country           object
Continent         object
dtype: object

Створіть нову колонку на основі двох існуючих.

In [7]:
df['New'] = df['CurrentRanking'] + df['HighestRanking']
df.head(10)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0    8/23/2012  199697               1               1         Brazil   
1     9/7/2016  188693               2               1            NaN   
2    6/24/2013  160026               3               1            NaN   
3    8/24/2015  119109               4               4      Lithuania   
4    4/20/2014  118149               5               5         Canada   
5   11/13/2012  116060               6               4  United States   
6    2/28/2014  114214               7               3          China   
7    11/8/2015  106314               8               8         Russia   
8    6/25/2010  103017               9               6        Austria   
9    7/20/2016  102460              10               9         Latvia   

       Continent  New  
0  South America    2  
1            NaN    3  
2            NaN    4  
3         Europe    8  
4  North America   10  
5  North America   10  
6           Asia   10  
7           Asia   16  
8         Europe   15  
9         Europe   19

RegisterDate  Points  CurrentRanking  HighestRanking    Country  \
0       8/23/2012  199697               1               1     Brazil   
1        9/7/2016  188693               2               1       None   
2       6/24/2013  160026               3               1       None   
3       8/24/2015  119109               4               4  Lithuania   
4       4/20/2014  118149               5               5     Canada   
...           ...     ...             ...             ...        ...   
4762   11/24/2010      14            4762             265    Belgium   
4763     1/1/2012      14            4763            1444       None   
4764     1/9/2012      14            4764            1444      India   
4765    1/15/2012      14            4765            1444       None   
4766    1/17/2012      14            4766            1444       None   

          Continent  NewColumn  
0     South America          2  
1              None          3  
2              None          4  
3            Europe          8  
4     North America         10  
...             ...        ...  
4762         Europe       5027  
4763           None       6207  
4764           Asia       6208  
4765           None       6209  
4766           None       6210  

[4767 rows x 7 columns]

Виведіть дві будь-які колонки з DataFrame.

In [46]:
print(df[['CurrentRanking', 'Country']])

      CurrentRanking    Country
0                  1     Brazil
1                  2        NaN
2                  3        NaN
3                  4  Lithuania
4                  5     Canada
...              ...        ...
4762            4762    Belgium
4763            4763        NaN
4764            4764      India
4765            4765        NaN
4766            4766        NaN

[4767 rows x 2 columns]


CurrentRanking    Country
0                  1     Brazil
1                  2       None
2                  3       None
3                  4  Lithuania
4                  5     Canada
...              ...        ...
4762            4762    Belgium
4763            4763       None
4764            4764      India
4765            4765       None
4766            4766       None

[4767 rows x 2 columns]

Виведіть рядок з  будь-яким індексом DataFrame.

In [47]:
df.loc[3]

RegisterDate      8/24/2015
Points               119109
CurrentRanking            4
HighestRanking            4
Country           Lithuania
Continent            Europe
C                         8
New                       8
Name: 3, dtype: object

RegisterDate      8/24/2015
Points               119109
CurrentRanking            4
HighestRanking            4
Country           Lithuania
Continent            Europe
NewColumn                 8
Name: 3, dtype: object

Виведіть всі елементи DataFrame, у яких значення колонки 'Country' не є 'None'.

In [51]:
df[df['Country'].notna()]

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0       8/23/2012  199697               1               1         Brazil   
3       8/24/2015  119109               4               4      Lithuania   
4       4/20/2014  118149               5               5         Canada   
5      11/13/2012  116060               6               4  United States   
6       2/28/2014  114214               7               3          China   
...           ...     ...             ...             ...            ...   
4757    8/29/2010      20            4757              73       Colombia   
4760   11/15/2010      16            4760             151         Israel   
4761    1/17/2012      16            4761            1201  United States   
4762   11/24/2010      14            4762             265        Belgium   
4764     1/9/2012      14            4764            1444          India   

          Continent     C   New  
0     South America     2     2  
3            Europe     8     8  
4     North America    10    10  
5     North America    10    10  
6              Asia    10    10  
...             ...   ...   ...  
4757  South America  4830  4830  
4760           Asia  4911  4911  
4761  North America  5962  5962  
4762         Europe  5027  5027  
4764           Asia  6208  6208  

[3500 rows x 8 columns]

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0       8/23/2012  199697               1               1         Brazil   
3       8/24/2015  119109               4               4      Lithuania   
4       4/20/2014  118149               5               5         Canada   
5      11/13/2012  116060               6               4  United States   
6       2/28/2014  114214               7               3          China   
...           ...     ...             ...             ...            ...   
4757    8/29/2010      20            4757              73       Colombia   
4760   11/15/2010      16            4760             151         Israel   
4761    1/17/2012      16            4761            1201  United States   
4762   11/24/2010      14            4762             265        Belgium   
4764     1/9/2012      14            4764            1444          India   

          Continent  NewColumn  
0     South America          2  
3            Europe          8  
4     North America         10  
5     North America         10  
6              Asia         10  
...             ...        ...  
4757  South America       4830  
4760           Asia       4911  
4761  North America       5962  
4762         Europe       5027  
4764           Asia       6208  

[3500 rows x 7 columns]

Видаліть будь-який рядочок з DataFrame.

In [52]:
df.drop(index=0)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
1        9/7/2016  188693               2               1            NaN   
2       6/24/2013  160026               3               1            NaN   
3       8/24/2015  119109               4               4      Lithuania   
4       4/20/2014  118149               5               5         Canada   
5      11/13/2012  116060               6               4  United States   
...           ...     ...             ...             ...            ...   
4762   11/24/2010      14            4762             265        Belgium   
4763     1/1/2012      14            4763            1444            NaN   
4764     1/9/2012      14            4764            1444          India   
4765    1/15/2012      14            4765            1444            NaN   
4766    1/17/2012      14            4766            1444            NaN   

          Continent     C   New  
1               NaN     3     3  
2               NaN     4     4  
3            Europe     8     8  
4     North America    10    10  
5     North America    10    10  
...             ...   ...   ...  
4762         Europe  5027  5027  
4763            NaN  6207  6207  
4764           Asia  6208  6208  
4765            NaN  6209  6209  
4766            NaN  6210  6210  

[4766 rows x 8 columns]

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0       8/23/2012  199697               1               1         Brazil   
2       6/24/2013  160026               3               1           None   
3       8/24/2015  119109               4               4      Lithuania   
4       4/20/2014  118149               5               5         Canada   
5      11/13/2012  116060               6               4  United States   
...           ...     ...             ...             ...            ...   
4762   11/24/2010      14            4762             265        Belgium   
4763     1/1/2012      14            4763            1444           None   
4764     1/9/2012      14            4764            1444          India   
4765    1/15/2012      14            4765            1444           None   
4766    1/17/2012      14            4766            1444           None   

          Continent  NewColumn  
0     South America          2  
2              None          4  
3            Europe          8  
4     North America         10  
5     North America         10  
...             ...        ...  
4762         Europe       5027  
4763           None       6207  
4764           Asia       6208  
4765           None       6209  
4766           None       6210  

[4766 rows x 7 columns]

Видаліть будь-яку колонку з DataFrame.

In [53]:
df.drop(columns='C')

RegisterDate  Points  CurrentRanking  HighestRanking    Country  \
0       8/23/2012  199697               1               1     Brazil   
1        9/7/2016  188693               2               1        NaN   
2       6/24/2013  160026               3               1        NaN   
3       8/24/2015  119109               4               4  Lithuania   
4       4/20/2014  118149               5               5     Canada   
...           ...     ...             ...             ...        ...   
4762   11/24/2010      14            4762             265    Belgium   
4763     1/1/2012      14            4763            1444        NaN   
4764     1/9/2012      14            4764            1444      India   
4765    1/15/2012      14            4765            1444        NaN   
4766    1/17/2012      14            4766            1444        NaN   

          Continent   New  
0     South America     2  
1               NaN     3  
2               NaN     4  
3            Europe     8  
4     North America    10  
...             ...   ...  
4762         Europe  5027  
4763            NaN  6207  
4764           Asia  6208  
4765            NaN  6209  
4766            NaN  6210  

[4767 rows x 7 columns]

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0       8/23/2012  199697               1               1         Brazil   
2       6/24/2013  160026               3               1           None   
3       8/24/2015  119109               4               4      Lithuania   
4       4/20/2014  118149               5               5         Canada   
5      11/13/2012  116060               6               4  United States   
...           ...     ...             ...             ...            ...   
4762   11/24/2010      14            4762             265        Belgium   
4763     1/1/2012      14            4763            1444           None   
4764     1/9/2012      14            4764            1444          India   
4765    1/15/2012      14            4765            1444           None   
4766    1/17/2012      14            4766            1444           None   

          Continent  
0     South America  
2              None  
3            Europe  
4     North America  
5     North America  
...             ...  
4762         Europe  
4763           None  
4764           Asia  
4765           None  
4766           None  

[4766 rows x 6 columns]

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3'.

In [54]:
df[df['CurrentRanking'].isin([1, 2, 3])]

RegisterDate  Points  CurrentRanking  HighestRanking Country      Continent  \
0    8/23/2012  199697               1               1  Brazil  South America   
1     9/7/2016  188693               2               1     NaN            NaN   
2    6/24/2013  160026               3               1     NaN            NaN   

   C  New  
0  2    2  
1  3    3  
2  4    4

RegisterDate  Points  CurrentRanking  HighestRanking Country      Continent
0    8/23/2012  199697               1               1  Brazil  South America
2    6/24/2013  160026               3               1    None           None

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3' та значення 'Country' - 'Brazil'.

In [55]:
df[(df['CurrentRanking'].isin([1, 2, 3])) & (df['Country'] == 'Brazil')]

RegisterDate  Points  CurrentRanking  HighestRanking Country      Continent  \
0    8/23/2012  199697               1               1  Brazil  South America   

   C  New  
0  2    2

RegisterDate  Points  CurrentRanking  HighestRanking Country      Continent
0    8/23/2012  199697               1               1  Brazil  South America

Для подальших завдань, створіть DataFrame, який буде містити перші 10 записів з оригінального DataFrame.

In [30]:
df_first_10 = df.head(10)
df_first_10

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0    8/23/2012  199697               1               1         Brazil   
1     9/7/2016  188693               2               1            NaN   
2    6/24/2013  160026               3               1            NaN   
3    8/24/2015  119109               4               4      Lithuania   
4    4/20/2014  118149               5               5         Canada   
5   11/13/2012  116060               6               4  United States   
6    2/28/2014  114214               7               3          China   
7    11/8/2015  106314               8               8         Russia   
8    6/25/2010  103017               9               6        Austria   
9    7/20/2016  102460              10               9         Latvia   

       Continent  
0  South America  
1            NaN  
2            NaN  
3         Europe  
4  North America  
5  North America  
6           Asia  
7           Asia  
8         Europe  
9         Europe

Виведіть всі значення з колонки 'HighestRanking' та скільки разів вони зустрічаються.

In [9]:
df_first_10['HighestRanking'].value_counts()

HighestRanking
1    3
4    2
5    1
3    1
8    1
6    1
9    1
Name: count, dtype: int64

4    3
1    2
5    1
3    1
8    1
6    1
9    1
Name: HighestRanking, dtype: int64

Виведіть усі унікальні значення з колонки 'HighestRanking'.

In [59]:
df_first_10['HighestRanking'].unique()

array([1, 4, 5, 3, 8, 6, 9])

array([1, 4, 5, 3, 8, 6, 9])

Застосуйте функцію map до DataFrame.

In [31]:
df_first_10 = df.head(10).copy()

country_codes = {
    'Brazil': 'BR',
    'Lithuania': 'LT',
    'Canada': 'CA',
    'United States': 'US',
    'China': 'CN',
    'Russia': 'RU',
    'Austria': 'AT',
    'Latvia': 'LV'
}

# Застосування методу map для скорочення назв країн
df_first_10.loc[:, 'CountryCode'] = df_first_10['Country'].map(country_codes)

# Замінити NaN на 'Not Found'
df_first_10['CountryCode'].fillna('Not Found')


0           BR
1    Not Found
2    Not Found
3           LT
4           CA
5           US
6           CN
7           RU
8           AT
9           LV
Name: CountryCode, dtype: object

0           South America
2     Continent not found
3                  Europe
4           North America
5           North America
6                    Asia
7                    Asia
8                  Europe
9                  Europe
10                   Asia
Name: Continent, dtype: object

Відсортуйте дані по колонці 'HighestRanking'.

In [72]:
df.sort_values(by='HighestRanking')

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0     8/23/2012  199697               1               1         Brazil   
2     6/24/2013  160026               3               1           None   
6     2/28/2014  114214               7               3          China   
3     8/24/2015  119109               4               4      Lithuania   
5    11/13/2012  116060               6               4  United States   
10    2/16/2011  102417              11               4          Japan   
4     4/20/2014  118149               5               5         Canada   
8     6/25/2010  103017               9               6        Austria   
7     11/8/2015  106314               8               8         Russia   
9     7/20/2016  102460              10               9         Latvia   

        Continent  
0   South America  
2            None  
6            Asia  
3          Europe  
5   North America  
10           Asia  
4   North America  
8          Europe  
7            Asia  
9          Europe

Згрупуйте дані по трьох колонках.

In [33]:
df.groupby(['HighestRanking', 'Country', 'Points']).size().reset_index(name='Count')

HighestRanking         Country  Points  Count
0                  1          Brazil   22923      1
1                  1          Brazil  199697      1
2                  1          Canada    3326      1
3                  1          Russia    9898      1
4                  1          Russia   88845      1
...              ...             ...     ...    ...
3479            3246          Russia    1116      1
3480            3251          Russia    1109      1
3481            3273  United Kingdom    1084      1
3482            3408           India     650      1
3483            3409           India     650      1

[3484 rows x 4 columns]

RegisterDate  Points  \
Continent     Country       HighestRanking                         
Asia          China         3                          1       1   
              Japan         4                          1       1   
              Russia        8                          1       1   
Europe        Austria       6                          1       1   
              Latvia        9                          1       1   
              Lithuania     4                          1       1   
None          None          1                          1       1   
North America Canada        5                          1       1   
              United States 4                          1       1   
South America Brazil        1                          1       1   

                                            CurrentRanking  
Continent     Country       HighestRanking                  
Asia          China         3                            1  
              Japan         4                            1  
              Russia        8                            1  
Europe        Austria       6                            1  
              Latvia        9                            1  
              Lithuania     4                            1  
None          None          1                            1  
North America Canada        5                            1  
              United States 4                            1  
South America Brazil        1                            1

Застосуйте функції агрегації до даних.

In [76]:
# ваш код тут

Points            1241463
HighestRanking          1
dtype: int64

Застосуйте функцію `query()` до даних.

In [35]:
aggregated_df = df.groupby('Country').agg({
    'HighestRanking': ['mean', 'min', 'max'],
    'Points': 'sum',
    'CurrentRanking': 'count'
})
aggregated_df


HighestRanking               Points CurrentRanking
                               mean   min   max      sum          count
Country                                                                
Algeria                   51.000000     9    93     1726              2
Argentina               1261.857143    55  2296    18765              7
Armenia                 1746.166667  1293  1990     6547              6
Australia                579.087912     3  2421   261300             91
Austria                  344.000000     6  1946   165944             10
...                             ...   ...   ...      ...            ...
United Arab Emirates     767.000000   134  1990    11682              5
United Kingdom           660.281879     1  3273   786380            149
United States            699.972590     1  3193  5698751           1058
Venezuela                985.500000   390  1581     1114              2
Vietnam                 1068.941176    91  2893   107607             17

[83 rows x 5 columns]

Empty DataFrame
Columns: [RegisterDate, Points, CurrentRanking, HighestRanking, Country, Continent]
Index: []

## Робота з бібліотекою Polars.

### Імпорт бібліотеки. 

In [36]:
import polars as pl

### Завантаження даних у DataFrame.

In [37]:
df = pl.read_csv("data.csv")

shape: (4_767, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None      ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None      ┆ None          │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …             │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None      ┆ None          │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None      ┆ None          │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None      ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴───────────────┘

Виведіть перші 10 рядочків з DataFrame.

In [38]:
df.head(10)

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil        ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None          ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None          ┆ None          │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania     ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada        ┆ North America │
│ 11/13/2012   ┆ 116060 ┆ 6              ┆ 4              ┆ United States ┆ North America │
│ 2/28/2014    ┆ 114214 ┆ 7              ┆ 3              ┆ China         ┆ Asia          │
│ 11/8/2015    ┆ 106314 ┆ 8              ┆ 8              ┆ Russia        ┆ Asia          │
│ 6/25/2010    ┆ 103017 ┆ 9              ┆ 6              ┆ Austria       ┆ Europe        │
│ 7/20/2016    ┆ 102460 ┆ 10             ┆ 9              ┆ Latvia        ┆ Europe        │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil        ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None          ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None          ┆ None          │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania     ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada        ┆ North America │
│ 11/13/2012   ┆ 116060 ┆ 6              ┆ 4              ┆ United States ┆ North America │
│ 2/28/2014    ┆ 114214 ┆ 7              ┆ 3              ┆ China         ┆ Asia          │
│ 11/8/2015    ┆ 106314 ┆ 8              ┆ 8              ┆ Russia        ┆ Asia          │
│ 6/25/2010    ┆ 103017 ┆ 9              ┆ 6              ┆ Austria       ┆ Europe        │
│ 7/20/2016    ┆ 102460 ┆ 10             ┆ 9              ┆ Latvia        ┆ Europe        │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Виведіть останні 10 рядочків з DataFrame.

In [39]:
df.tail(10)

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/29/2010    ┆ 20     ┆ 4757           ┆ 73             ┆ Colombia      ┆ South America │
│ 11/11/2010   ┆ 19     ┆ 4758           ┆ 117            ┆ None          ┆ None          │
│ 11/24/2011   ┆ 18     ┆ 4759           ┆ 1081           ┆ None          ┆ None          │
│ 11/15/2010   ┆ 16     ┆ 4760           ┆ 151            ┆ Israel        ┆ Asia          │
│ 1/17/2012    ┆ 16     ┆ 4761           ┆ 1201           ┆ United States ┆ North America │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium       ┆ Europe        │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None          ┆ None          │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India         ┆ Asia          │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None          ┆ None          │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None          ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/29/2010    ┆ 20     ┆ 4757           ┆ 73             ┆ Colombia      ┆ South America │
│ 11/11/2010   ┆ 19     ┆ 4758           ┆ 117            ┆ None          ┆ None          │
│ 11/24/2011   ┆ 18     ┆ 4759           ┆ 1081           ┆ None          ┆ None          │
│ 11/15/2010   ┆ 16     ┆ 4760           ┆ 151            ┆ Israel        ┆ Asia          │
│ 1/17/2012    ┆ 16     ┆ 4761           ┆ 1201           ┆ United States ┆ North America │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium       ┆ Europe        │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None          ┆ None          │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India         ┆ Asia          │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None          ┆ None          │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None          ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Виведіть випадкові 10 рядочків з DataFrame.

In [40]:
df.sample(10)

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/26/2010    ┆ 2476   ┆ 2309           ┆ 395            ┆ United States ┆ North America │
│ 4/18/2016    ┆ 2554   ┆ 2268           ┆ 1739           ┆ Italy         ┆ Europe        │
│ 5/30/2012    ┆ 118    ┆ 4612           ┆ 396            ┆ None          ┆ None          │
│ 8/22/2010    ┆ 1878   ┆ 2710           ┆ 154            ┆ Germany       ┆ Europe        │
│ 7/4/2013     ┆ 350    ┆ 4213           ┆ 1211           ┆ None          ┆ None          │
│ 12/19/2014   ┆ 1429   ┆ 3052           ┆ 1929           ┆ Taiwan        ┆ Asia          │
│ 1/7/2017     ┆ 22359  ┆ 233            ┆ 176            ┆ United States ┆ North America │
│ 7/20/2012    ┆ 244    ┆ 4371           ┆ 232            ┆ None          ┆ None          │
│ 12/29/2015   ┆ 5213   ┆ 1278           ┆ 1054           ┆ Russia        ┆ Asia          │
│ 12/23/2015   ┆ 1076   ┆ 3336           ┆ 1975           ┆ Brazil        ┆ South America │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 4/30/2015    ┆ 2167   ┆ 2503           ┆ 1231           ┆ Canada        ┆ North America │
│ 4/18/2016    ┆ 2554   ┆ 2268           ┆ 1739           ┆ Italy         ┆ Europe        │
│ 4/16/2012    ┆ 581    ┆ 3904           ┆ 263            ┆ None          ┆ None          │
│ 4/20/2015    ┆ 56483  ┆ 41             ┆ 19             ┆ Canada        ┆ North America │
│ 5/13/2014    ┆ 9933   ┆ 626            ┆ 626            ┆ United States ┆ North America │
│ 7/21/2015    ┆ 2485   ┆ 2305           ┆ 1175           ┆ India         ┆ Asia          │
│ 7/1/2013     ┆ 2123   ┆ 2534           ┆ 1104           ┆ Poland        ┆ Europe        │
│ 7/22/2013    ┆ 5358   ┆ 1241           ┆ 165            ┆ China         ┆ Asia          │
│ 7/2/2010     ┆ 26     ┆ 4750           ┆ 98             ┆ Canada        ┆ North America │
│ 7/3/2011     ┆ 55     ┆ 4712           ┆ 420            ┆ None          ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Виведіть розмірність DataFrame.

In [41]:
df.shape

(4767, 6)

(4767, 6)

Виведіть назви колонок DataFrame.

In [42]:
df.columns

['RegisterDate',
 'Points',
 'CurrentRanking',
 'HighestRanking',
 'Country',
 'Continent']

['RegisterDate',
 'Points',
 'CurrentRanking',
 'HighestRanking',
 'Country',
 'Continent']

Виведіть інформацію про типи даних елементів у DataFrame.

In [43]:
df.dtypes

[String, Int64, Int64, Int64, String, String]

[String, Int64, Int64, Int64, String, String]

Створіть нову колонку на основі двох існуючих.

In [44]:
df.with_columns((df["CurrentRanking"] +df["HighestRanking"]).alias("New"))

shape: (4_767, 7)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬───────────────┬──────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     ┆ New  │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---           ┆ ---  │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str           ┆ i64  │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪═══════════════╪══════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America ┆ 2    │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None      ┆ None          ┆ 3    │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None      ┆ None          ┆ 4    │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        ┆ 8    │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America ┆ 10   │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …             ┆ …    │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        ┆ 5027 │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None      ┆ None          ┆ 6207 │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          ┆ 6208 │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None      ┆ None          ┆ 6209 │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None      ┆ None          ┆ 6210 │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴───────────────┴──────┘

shape: (4_767, 7)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬───────────────┬───────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     ┆ NewColumn │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---           ┆ ---       │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str           ┆ i64       │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪═══════════════╪═══════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America ┆ 2         │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None      ┆ None          ┆ 3         │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None      ┆ None          ┆ 4         │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        ┆ 8         │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America ┆ 10        │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …             ┆ …         │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        ┆ 5027      │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None      ┆ None          ┆ 6207      │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          ┆ 6208      │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None      ┆ None          ┆ 6209      │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None      ┆ None          ┆ 6210      │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴───────────────┴───────────┘

Виведіть дві будь-які колонки з DataFrame.

In [45]:
df[["Points", "CurrentRanking"]]

shape: (4_767, 2)
┌────────┬────────────────┐
│ Points ┆ CurrentRanking │
│ ---    ┆ ---            │
│ i64    ┆ i64            │
╞════════╪════════════════╡
│ 199697 ┆ 1              │
│ 188693 ┆ 2              │
│ 160026 ┆ 3              │
│ 119109 ┆ 4              │
│ 118149 ┆ 5              │
│ …      ┆ …              │
│ 14     ┆ 4762           │
│ 14     ┆ 4763           │
│ 14     ┆ 4764           │
│ 14     ┆ 4765           │
│ 14     ┆ 4766           │
└────────┴────────────────┘

shape: (4_767, 2)
┌────────────────┬───────────┐
│ CurrentRanking ┆ Country   │
│ ---            ┆ ---       │
│ i64            ┆ str       │
╞════════════════╪═══════════╡
│ 1              ┆ Brazil    │
│ 2              ┆ None      │
│ 3              ┆ None      │
│ 4              ┆ Lithuania │
│ 5              ┆ Canada    │
│ …              ┆ …         │
│ 4762           ┆ Belgium   │
│ 4763           ┆ None      │
│ 4764           ┆ India     │
│ 4765           ┆ None      │
│ 4766           ┆ None      │
└────────────────┴───────────┘

Виведіть рядок з  будь-яким індексом DataFrame.

In [46]:
df[1]

shape: (1, 6)
┌──────────────┬────────┬────────────────┬────────────────┬─────────┬───────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country ┆ Continent │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---     ┆ ---       │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str     ┆ str       │
╞══════════════╪════════╪════════════════╪════════════════╪═════════╪═══════════╡
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None    ┆ None      │
└──────────────┴────────┴────────────────┴────────────────┴─────────┴───────────┘

('1/17/2012', 41478, 84, 14, 'Netherlands', 'Europe', 98)

Виведіть всі елементи DataFrame, у яких значення колонки 'Country' не є 'None'.

In [48]:
df.filter(pl.col('Country') != 'None')

shape: (3_500, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil        ┆ South America │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania     ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada        ┆ North America │
│ 11/13/2012   ┆ 116060 ┆ 6              ┆ 4              ┆ United States ┆ North America │
│ 2/28/2014    ┆ 114214 ┆ 7              ┆ 3              ┆ China         ┆ Asia          │
│ …            ┆ …      ┆ …              ┆ …              ┆ …             ┆ …             │
│ 8/29/2010    ┆ 20     ┆ 4757           ┆ 73             ┆ Colombia      ┆ South America │
│ 11/15/2010   ┆ 16     ┆ 4760           ┆ 151            ┆ Israel        ┆ Asia          │
│ 1/17/2012    ┆ 16     ┆ 4761           ┆ 1201           ┆ United States ┆ North America │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium       ┆ Europe        │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India         ┆ Asia          │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

shape: (3_500, 7)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬────────────────┬───────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent      ┆ NewColumn │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---            ┆ ---       │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str            ┆ i64       │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪════════════════╪═══════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America  ┆ 2         │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe         ┆ 8         │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America  ┆ 10        │
│ 11/13/2012   ┆ 116060 ┆ 6              ┆ 4              ┆ United    ┆ North America  ┆ 10        │
│              ┆        ┆                ┆                ┆ States    ┆                ┆           │
│ 2/28/2014    ┆ 114214 ┆ 7              ┆ 3              ┆ China     ┆ Asia           ┆ 10        │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …              ┆ …         │
│ 8/29/2010    ┆ 20     ┆ 4757           ┆ 73             ┆ Colombia  ┆ South America  ┆ 4830      │
│ 11/15/2010   ┆ 16     ┆ 4760           ┆ 151            ┆ Israel    ┆ Asia           ┆ 4911      │
│ 1/17/2012    ┆ 16     ┆ 4761           ┆ 1201           ┆ United    ┆ North America  ┆ 5962      │
│              ┆        ┆                ┆                ┆ States    ┆                ┆           │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe         ┆ 5027      │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia           ┆ 6208      │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴────────────────┴───────────┘

Видаліть будь-яку колонку з DataFrame.

In [50]:
df.drop('Points')

shape: (4_767, 5)
┌──────────────┬────────────────┬────────────────┬───────────┬───────────────┐
│ RegisterDate ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     │
│ ---          ┆ ---            ┆ ---            ┆ ---       ┆ ---           │
│ str          ┆ i64            ┆ i64            ┆ str       ┆ str           │
╞══════════════╪════════════════╪════════════════╪═══════════╪═══════════════╡
│ 8/23/2012    ┆ 1              ┆ 1              ┆ Brazil    ┆ South America │
│ 9/7/2016     ┆ 2              ┆ 1              ┆ None      ┆ None          │
│ 6/24/2013    ┆ 3              ┆ 1              ┆ None      ┆ None          │
│ 8/24/2015    ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        │
│ 4/20/2014    ┆ 5              ┆ 5              ┆ Canada    ┆ North America │
│ …            ┆ …              ┆ …              ┆ …         ┆ …             │
│ 11/24/2010   ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        │
│ 1/1/2012     ┆ 4763           ┆ 1444           ┆ None      ┆ None          │
│ 1/9/2012     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          │
│ 1/15/2012    ┆ 4765           ┆ 1444           ┆ None      ┆ None          │
│ 1/17/2012    ┆ 4766           ┆ 1444           ┆ None      ┆ None          │
└──────────────┴────────────────┴────────────────┴───────────┴───────────────┘

shape: (4_767, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None      ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None      ┆ None          │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …             │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None      ┆ None          │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None      ┆ None          │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None      ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴───────────────┘

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3'.

In [52]:
df.filter(pl.col('CurrentRanking').is_in([1, 2, 3]))

shape: (3, 6)
┌──────────────┬────────┬────────────────┬────────────────┬─────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---     ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str     ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil  ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None    ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None    ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴─────────┴───────────────┘

In [ ]:
df.filter(pl.col('CurrentRanking').is_in([1, 2, 3]))

shape: (3, 6)
┌──────────────┬────────┬────────────────┬────────────────┬─────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---     ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str     ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil  ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None    ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None    ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴─────────┴───────────────┘

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3' та значення 'Country' - 'Brazil'.

In [53]:
df.filter(
    (pl.col('CurrentRanking').is_in([1, 2, 3])) & 
    (pl.col('Country') == 'Brazil')
)

shape: (1, 6)
┌──────────────┬────────┬────────────────┬────────────────┬─────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---     ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str     ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil  ┆ South America │
└──────────────┴────────┴────────────────┴────────────────┴─────────┴───────────────┘

shape: (1, 6)
┌──────────────┬────────┬────────────────┬────────────────┬─────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---     ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str     ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil  ┆ South America │
└──────────────┴────────┴────────────────┴────────────────┴─────────┴───────────────┘

Для подальших завдань, створіть DataFrame, який буде містити випадкові 10 записів з оригінального DataFrame.

In [54]:
random_sample_df = df.sample(n=10)

Виведіть всі значення з колонки 'HighestRanking' та скільки разів вони зустрічаються.

In [55]:
random_sample_df['HighestRanking'].value_counts()

shape: (10, 2)
┌────────────────┬───────┐
│ HighestRanking ┆ count │
│ ---            ┆ ---   │
│ i64            ┆ u32   │
╞════════════════╪═══════╡
│ 553            ┆ 1     │
│ 160            ┆ 1     │
│ 2235           ┆ 1     │
│ 276            ┆ 1     │
│ 2094           ┆ 1     │
│ 478            ┆ 1     │
│ 1650           ┆ 1     │
│ 3              ┆ 1     │
│ 572            ┆ 1     │
│ 1400           ┆ 1     │
└────────────────┴───────┘

shape: (10, 2)
┌────────────────┬───────┐
│ HighestRanking ┆ count │
│ ---            ┆ ---   │
│ i64            ┆ u32   │
╞════════════════╪═══════╡
│ 616            ┆ 1     │
│ 666            ┆ 1     │
│ 865            ┆ 1     │
│ 46             ┆ 1     │
│ 2080           ┆ 1     │
│ 189            ┆ 1     │
│ 251            ┆ 1     │
│ 373            ┆ 1     │
│ 902            ┆ 1     │
│ 511            ┆ 1     │
└────────────────┴───────┘

Виведіть усі унікальні значення з колонки 'HighestRanking'.

In [56]:
random_sample_df['HighestRanking'].unique()

shape: (10,)
Series: 'HighestRanking' [i64]
[
	3
	160
	276
	478
	553
	572
	1400
	1650
	2094
	2235
]

shape: (10,)
Series: 'HighestRanking' [i64]
[
	46
	189
	251
	373
	511
	616
	666
	865
	902
	2080
]

Застосуйте функцію map до DataFrame.

In [61]:
country_codes = {
    'Brazil': 'BR',
    'Lithuania': 'LT',
    'Canada': 'CA',
    'United States': 'US',
    'China': 'CN',
    'Russia': 'RU',
    'Austria': 'AT',
    'Latvia': 'LV',
}

# Перетворення словника у DataFrame
mapper = pl.DataFrame({
    "keys": list(country_codes.keys()),
    "values": list(country_codes.values())
})

# Вибір колонки 'Country' для з'єднання
filtered_keys = random_sample_df.select(pl.col('Country'))

# Виконання з'єднання
result = filtered_keys.join(mapper, left_on="Country", right_on="keys", how="left")

result

shape: (10, 2)
┌────────────────┬────────┐
│ Country        ┆ values │
│ ---            ┆ ---    │
│ str            ┆ str    │
╞════════════════╪════════╡
│ India          ┆ null   │
│ France         ┆ null   │
│ None           ┆ null   │
│ None           ┆ null   │
│ Netherlands    ┆ null   │
│ United States  ┆ US     │
│ United Kingdom ┆ null   │
│ Portugal       ┆ null   │
│ Norway         ┆ null   │
│ None           ┆ null   │
└────────────────┴────────┘

shape: (10,)
Series: 'Continent' [str]
[
	"Continent not found"
	"Asia"
	"Europe"
	"North America"
	"Asia"
	"North America"
	"North America"
	"North America"
	"Continent not found"
	"Asia"
]

Відсортуйте дані по колонці 'HighestRanking'.

In [62]:
df.sort('HighestRanking')

shape: (4_767, 6)
┌──────────────┬────────┬────────────────┬────────────────┬────────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country        ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---            ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str            ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪════════════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil         ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None           ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None           ┆ None          │
│ 12/13/2013   ┆ 88845  ┆ 16             ┆ 1              ┆ Russia         ┆ Asia          │
│ 1/27/2011    ┆ 28330  ┆ 162            ┆ 1              ┆ Spain          ┆ Europe        │
│ …            ┆ …      ┆ …              ┆ …              ┆ …              ┆ …             │
│ 6/19/2017    ┆ 1109   ┆ 3304           ┆ 3251           ┆ Russia         ┆ Asia          │
│ 5/22/2017    ┆ 1084   ┆ 3327           ┆ 3273           ┆ United Kingdom ┆ Europe        │
│ 11/5/2016    ┆ 650    ┆ 3808           ┆ 3408           ┆ India          ┆ Asia          │
│ 3/25/2017    ┆ 650    ┆ 3809           ┆ 3409           ┆ India          ┆ Asia          │
│ 6/6/2016     ┆ 827    ┆ 3570           ┆ 3517           ┆ None           ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴────────────────┴───────────────┘

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/19/2012    ┆ 6464   ┆ 1040           ┆ 46             ┆ United States ┆ North America │
│ 2/5/2016     ┆ 23460  ┆ 210            ┆ 189            ┆ United States ┆ North America │
│ 11/23/2010   ┆ 45     ┆ 4727           ┆ 251            ┆ Netherlands   ┆ Europe        │
│ 12/2/2015    ┆ 15131  ┆ 380            ┆ 373            ┆ Japan         ┆ Asia          │
│ 3/23/2014    ┆ 1788   ┆ 2763           ┆ 511            ┆ United States ┆ North America │
│ 3/4/2013     ┆ 4827   ┆ 1363           ┆ 616            ┆ Japan         ┆ Asia          │
│ 4/29/2015    ┆ 7504   ┆ 879            ┆ 666            ┆ None          ┆ None          │
│ 5/22/2016    ┆ 6243   ┆ 1077           ┆ 865            ┆ None          ┆ None          │
│ 12/27/2014   ┆ 2974   ┆ 2050           ┆ 902            ┆ Thailand      ┆ Asia          │
│ 2/23/2017    ┆ 2378   ┆ 2361           ┆ 2080           ┆ United States ┆ North America │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Згрупуйте дані по трьох колонках.

In [76]:
grouped = random_sample_df.group_by(['HighestRanking', 'Points', 'CurrentRanking']).agg([
    pl.len().alias('Count'),  # Підрахунок кількості записів у кожній групі
    pl.sum('Points').alias('TotalPoints')  # Підрахунок загальної кількості балів
])


shape: (10, 4)
┌───────────────┬───────────────┬────────────────┬─────┐
│ Continent     ┆ Country       ┆ HighestRanking ┆ len │
│ ---           ┆ ---           ┆ ---            ┆ --- │
│ str           ┆ str           ┆ i64            ┆ u32 │
╞═══════════════╪═══════════════╪════════════════╪═════╡
│ North America ┆ United States ┆ 2080           ┆ 1   │
│ North America ┆ United States ┆ 511            ┆ 1   │
│ None          ┆ None          ┆ 666            ┆ 1   │
│ Asia          ┆ Japan         ┆ 373            ┆ 1   │
│ Asia          ┆ Japan         ┆ 616            ┆ 1   │
│ North America ┆ United States ┆ 46             ┆ 1   │
│ None          ┆ None          ┆ 865            ┆ 1   │
│ Asia          ┆ Thailand      ┆ 902            ┆ 1   │
│ North America ┆ United States ┆ 189            ┆ 1   │
│ Europe        ┆ Netherlands   ┆ 251            ┆ 1   │
└───────────────┴───────────────┴────────────────┴─────┘

Застосуйте функції агрегації до даних.

shape: (4, 2)
┌───────────────┬───────┐
│ Continent     ┆ range │
│ ---           ┆ ---   │
│ str           ┆ i64   │
╞═══════════════╪═══════╡
│ Europe        ┆ 0     │
│ None          ┆ 198   │
│ North America ┆ 2553  │
│ Asia          ┆ 1670  │
└───────────────┴───────┘