# Лабораторна робота #7.
## Класифікація.

#### Імпортуйте необхідні бібліотеки.

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
%matplotlib inline


## Дані.

#### Зчитайте дані з файлу `advertising.csv` у датафрейм `advertising` та перевірте датафрейм переглянувши перші 5 записів у ньому.

In [13]:
advertising= pd.read_csv('advertising.csv')
advertising.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

У цій частині лабораторної роботи завданням є класифікація записів по полю `Clicked on Ad`, тобто чи натиснув користувач на рекламу на сайті.

#### Виведіть інформацію про датафрейм  `advertising`.

In [14]:
advertising.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.3+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [15]:
advertising.describe()

Daily Time Spent on Site          Age   Area Income  \
count               1000.000000  1000.000000   1000.000000   
mean                  65.000200    36.009000  55000.000080   
std                   15.853615     8.785562  13414.634022   
min                   32.600000    19.000000  13996.500000   
25%                   51.360000    29.000000  47031.802500   
50%                   68.215000    35.000000  57012.300000   
75%                   78.547500    42.000000  65470.635000   
max                   91.430000    61.000000  79484.800000   

       Daily Internet Usage         Male  Clicked on Ad  
count           1000.000000  1000.000000     1000.00000  
mean             180.000100     0.481000        0.50000  
std               43.902339     0.499889        0.50025  
min              104.780000     0.000000        0.00000  
25%              138.830000     0.000000        0.00000  
50%              183.130000     0.000000        0.50000  
75%              218.792500     1.000000        1.00000  
max              269.960000     1.000000        1.00000

Daily Time Spent on Site          Age   Area Income  \
count               1000.000000  1000.000000   1000.000000   
mean                  65.000200    36.009000  55000.000080   
std                   15.853615     8.785562  13414.634022   
min                   32.600000    19.000000  13996.500000   
25%                   51.360000    29.000000  47031.802500   
50%                   68.215000    35.000000  57012.300000   
75%                   78.547500    42.000000  65470.635000   
max                   91.430000    61.000000  79484.800000   

       Daily Internet Usage         Male  Clicked on Ad  
count           1000.000000  1000.000000     1000.00000  
mean             180.000100     0.481000        0.50000  
std               43.902339     0.499889        0.50025  
min              104.780000     0.000000        0.00000  
25%              138.830000     0.000000        0.00000  
50%              183.130000     0.000000        0.50000  
75%              218.792500     1.000000        1.00000  
max              269.960000     1.000000        1.00000

## Попередня обробка даних.

#### Видаліть з датафрейму стовпчики, які не мають подаватись на вхід моделі.

In [16]:
advertising = advertising.drop(['Ad Topic Line', 'City', 'Country', 'Timestamp'], axis=1)
advertising.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
0                     68.95   35     61833.90                256.09     0   
1                     80.23   31     68441.85                193.77     1   
2                     69.47   26     59785.94                236.50     0   
3                     74.15   29     54806.18                245.89     1   
4                     68.37   35     73889.99                225.58     0   

   Clicked on Ad  
0              0  
1              0  
2              0  
3              0  
4              0

## Поділ даних на тестовий та тренувальні набори.

#### Створіть тестовий та тренувальний набори даних з датафрейму `advertising`. Задайте параметр `random_state=101`.

In [20]:
X = advertising.drop('Clicked on Ad', axis=1)  # Вхідні змінні
y = advertising['Clicked on Ad']               # Цільова змінна

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

#### Виведіть 5 перших записів у тестових та тренувальних наборах даних:

X_train:

In [23]:
X_train.head() 

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
290                     50.52   31     72270.88                171.62     0
167                     86.06   31     53767.12                219.72     1
486                     83.97   40     66291.67                158.42     1
683                     76.83   28     67990.84                192.81     0
876                     67.39   44     51257.26                107.19     0

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
290                     50.52   31     72270.88                171.62     0
167                     86.06   31     53767.12                219.72     1
486                     83.97   40     66291.67                158.42     1
683                     76.83   28     67990.84                192.81     0
876                     67.39   44     51257.26                107.19     0

X_test:

In [24]:
X_test.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
545                     42.60   55     55121.65                168.29     0
298                     80.39   31     66269.49                214.74     0
109                     74.02   32     72272.90                210.54     0
837                     55.77   49     55942.04                117.33     1
194                     77.20   33     49325.48                254.05     1

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
545                     42.60   55     55121.65                168.29     0
298                     80.39   31     66269.49                214.74     0
109                     74.02   32     72272.90                210.54     0
837                     55.77   49     55942.04                117.33     1
194                     77.20   33     49325.48                254.05     1

y_train:

In [25]:
y_train.head()

290    1
167    0
486    0
683    0
876    1
Name: Clicked on Ad, dtype: int64

290    1
167    0
486    0
683    0
876    1
Name: Clicked on Ad, dtype: int64

y_test:

In [26]:
y_test.head()

545    1
298    0
109    0
837    1
194    0
Name: Clicked on Ad, dtype: int64

545    1
298    0
109    0
837    1
194    0
Name: Clicked on Ad, dtype: int64

## Логістична регресійна модель.

#### Створіть логістичну модель.

In [40]:
logistic_model = LogisticRegression(max_iter=100)

logistic_model.fit(X_train, y_train)

C:\Users\Rostyk\PycharmProjects\engeneering 7\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

LogisticRegression()

#### Натренуйте створену модель.

C:\Users\Rostyk\PycharmProjects\engeneering 7\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

LogisticRegression()

#### Класифікуйте тестові дані.

In [41]:
y_pred = logistic_model.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0])

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0], d

#### Виведіть матрицю конфузії моделі:

In [45]:
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[149,   8],
       [ 14, 129]])

[[149   8]
 [ 14 129]]


#### Виведіть характеристики моделі:

In [50]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.91      0.95      0.93       157
           1       0.94      0.90      0.92       143

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



              precision    recall  f1-score   support

           0       0.91      0.95      0.93       157
           1       0.94      0.90      0.92       143

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



##  K найближчих сусідів.

#### Створіть модель.

In [59]:
knn_model = KNeighborsClassifier(n_neighbors=5)

KNeighborsClassifier(n_neighbors=1)

#### Натренуйте модель.

In [60]:
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

KNeighborsClassifier(n_neighbors=1)

#### Класифікуйте тестові дані.

In [62]:
y_pred_knn = knn_model.predict(X_test)
y_pred_knn

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0])

E:\Anaconda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0], d

#### Виведіть матрицю конфузії моделі:

In [63]:
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)
conf_matrix_knn

array([[120,  37],
       [ 47,  96]])

[[127  30]
 [ 31 112]]


#### Виведіть характеристики моделі:

In [64]:
report_knn = classification_report(y_test, y_pred_knn)
print(report_knn)

              precision    recall  f1-score   support

           0       0.72      0.76      0.74       157
           1       0.72      0.67      0.70       143

    accuracy                           0.72       300
   macro avg       0.72      0.72      0.72       300
weighted avg       0.72      0.72      0.72       300



              precision    recall  f1-score   support

           0       0.80      0.81      0.81       157
           1       0.79      0.78      0.79       143

    accuracy                           0.80       300
   macro avg       0.80      0.80      0.80       300
weighted avg       0.80      0.80      0.80       300



## Алгоритм опорних векторів.

#### Створіть модель. Задайте значення праметру `random_state=101`.

In [68]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear',random_state=101)

SVC(kernel='linear', random_state=101)

#### Натренуйте модель.

In [69]:
svm_model.fit(X_train, y_train)

SVC(kernel='linear', random_state=101)

SVC(kernel='linear', random_state=101)

#### Класифікуйте тестові дані.

In [70]:
y_pred_svm = svm_model.predict(X_test)
y_pred_svm

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0])

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0], d

#### Виведіть матрицю конфузії моделі.

In [71]:
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
conf_matrix_svm

array([[157,   0],
       [  6, 137]])

[[127  30]
 [ 31 112]]


#### Виведіть характеристики моделі.

In [72]:
report_svm = classification_report(y_test, y_pred_svm)

print(report_svm)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       157
           1       1.00      0.96      0.98       143

    accuracy                           0.98       300
   macro avg       0.98      0.98      0.98       300
weighted avg       0.98      0.98      0.98       300



              precision    recall  f1-score   support

           0       0.80      0.81      0.81       157
           1       0.79      0.78      0.79       143

    accuracy                           0.80       300
   macro avg       0.80      0.80      0.80       300
weighted avg       0.80      0.80      0.80       300



## Алгортим машинного навчання на дереві прийняття рішень.

#### Створіть модель. Задайте значення праметру `random_state=101`.

In [73]:
from sklearn.tree import DecisionTreeClassifier
decision_tree_model = DecisionTreeClassifier(random_state=101)

DecisionTreeClassifier(criterion='entropy', random_state=101)

#### Натренуйте модель.

In [74]:
decision_tree_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=101)

DecisionTreeClassifier(criterion='entropy', random_state=101)

#### Класифікуйте тестові дані.

In [75]:
y_pred_tree = decision_tree_model.predict(X_test)
y_pred_tree

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0])

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0], d

#### Виведіть матрицю конфузії моделі.

In [76]:
conf_matrix_tree = confusion_matrix(y_test, y_pred_tree)

print(conf_matrix_tree)

[[149   8]
 [  7 136]]


[[148   9]
 [  8 135]]


#### Виведіть характеристики моделі.

In [77]:
report_tree = classification_report(y_test, y_pred_tree)

print(report_tree)

              precision    recall  f1-score   support

           0       0.96      0.95      0.95       157
           1       0.94      0.95      0.95       143

    accuracy                           0.95       300
   macro avg       0.95      0.95      0.95       300
weighted avg       0.95      0.95      0.95       300



              precision    recall  f1-score   support

           0       0.95      0.94      0.95       157
           1       0.94      0.94      0.94       143

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



## Наївний Баєсівський класифікатор.

#### Створіть модель. Задайте значення праметру `random_state=101`.

In [78]:
from sklearn.naive_bayes import GaussianNB
naive_bayes_model = GaussianNB()

GaussianNB()

#### Натренуйте модель.

In [79]:
naive_bayes_model.fit(X_train, y_train)

GaussianNB()

GaussianNB()

#### Класифікуйте тестові дані.

In [80]:
y_pred_nb = naive_bayes_model.predict(X_test)
y_pred_nb

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0])

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0], d

#### Виведіть матрицю конфузії моделі.

In [81]:
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)

print(conf_matrix_nb)

[[154   3]
 [  5 138]]


[[154   3]
 [  5 138]]


#### Виведіть характеристики моделі.

In [82]:
report_nb = classification_report(y_test, y_pred_nb)

print(report_nb)

              precision    recall  f1-score   support

           0       0.97      0.98      0.97       157
           1       0.98      0.97      0.97       143

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



              precision    recall  f1-score   support

           0       0.97      0.98      0.97       157
           1       0.98      0.97      0.97       143

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



#### Зробіть висновок, який алгоритм найкраще підходить для роботи з даними `advertising`.

## Регресія.

У цій частині лабораторної роботи будуть використані дані певного інтернет магазину. Завдання лабораторної:
1. Передбачити, скільки грошей витратить в рік користувач (колонка 'Yearly Amount Spent' у даних) використовуючи різні регресійні моделі;
2. З допомогою множинної лінійної регресії визначити на чому компанії краще зосередити свої зусилля: розробка мобільного додатку, чи веб-сайту?

## Імпорт бібліотек.

In [ ]:
# ваш код тут

## Дані.

### Завантажте дані з файлу `Ecommerce Customers.csv` у датафрейм.

In [11]:
df = pd.read_csv('Ecommerce Customers.csv')
df = df.drop(columns=["Email",'Address','Avatar'])
df.head()

Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

Email  \
0      mstephenson@fernandez.com   
1              hduke@hotmail.com   
2               pallen@yahoo.com   
3        riverarebecca@gmail.com   
4  mstephens@davidson-herman.com   

                                             Address            Avatar  \
0       835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1     4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2  24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3   1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4  14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   

   Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

### Розділіть дані на тестовий та тренувальний набори.

In [12]:
X = df.drop(columns='Yearly Amount Spent')  # Видалити стовпець з цілею
y = df['Yearly Amount Spent']  # Цільова змінна
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)


## Множинна лінійна регресія.

### Створіть модель та натренуйте модель.

In [24]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([456.44186104, 402.72005312, 409.2531539 , 591.4310343 ,
       590.01437275, 548.82396607, 577.59737969, 715.44428115,
       473.7893446 , 545.9211364 , 337.8580314 , 500.38506697,
       552.93478041, 409.6038964 , 765.52590754, 545.83973731,
       693.25969124, 507.32416226, 573.10533175, 573.2076631 ,
       397.44989709, 555.0985107 , 458.19868141, 482.66899911,
       559.2655959 , 413.00946082, 532.25727408, 377.65464817,
       535.0209653 , 447.80070905, 595.54339577, 667.14347072,
       511.96042791, 573.30433971, 505.02260887, 565.30254655,
       460.38785393, 449.74727868, 422.87193429, 456.55615271,
       598.10493696, 449.64517443, 615.34948995, 511.88078685,
       504.37568058, 515.95249276, 568.64597718, 551.61444684,
       356.5552241 , 464.9759817 , 481.66007708, 534.2220025 ,
       256.28674001, 505.30810714, 520.01844434, 315.0298707 ,
       501.98080155, 387.03842642, 472.97419543, 432.8704675 ,
       539.79082198, 590.03070739, 752.86997652, 558.27

### Спрогнозуйте значення річних витрат для тестових даних.

In [25]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Виведення результатів
print(f"Середня квадратична помилка (MSE): {mse}")
print(f"Корінь середньоквадратичної помилки (RMSE): {rmse}")
print(f"Коефіцієнт детермінації (R^2): {r2}")

Середня квадратична помилка (MSE): 79.81305165097385
Корінь середньоквадратичної помилки (RMSE): 8.9338150669786
Коефіцієнт детермінації (R^2): 0.9890046246741235


### Оцініть модель.

MAE: 7.228148653430841
MSE: 79.81305165097457
RMSE: 8.93381506697864


### Ствріть новий датафрейм, у якому як дані використайте поле LinearRegression.coef_, а як стовпці - стовпці з датафрейму даних. Виведіть значення цих коефіцієнтів та зробіть висновок, на чому краще зосередитись компанії.

In [26]:
coefficients = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
coefficients

Coefficient
Avg. Session Length     25.981550
Time on App             38.590159
Time on Website          0.190405
Length of Membership    61.279097

Coeffecient
Avg. Session Length     25.981550
Time on App             38.590159
Time on Website          0.190405
Length of Membership    61.279097

## Поліноміальна лінійна регресія.

### Створіть та натренуйте модель.

In [21]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures
poly_model = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())
poly_model.fit(X_train, y_train)
y_pred_poly = poly_model.predict(X_test)
y_pred_poly


array([460.14247226, 405.9967866 , 408.15156754, 591.45137331,
       589.37335193, 548.86332048, 579.84759991, 712.94264698,
       472.69143394, 545.60944842, 337.60879994, 500.39750879,
       554.3026383 , 410.0051447 , 767.61431488, 546.29511932,
       693.28551606, 507.43237042, 573.93634876, 574.93347366,
       386.95940729, 554.9765691 , 457.75011218, 482.3866983 ,
       560.30911065, 414.68849327, 532.58993797, 379.40005693,
       535.95196512, 450.36876492, 597.13860366, 665.12463137,
       510.67487516, 573.66076082, 505.30046427, 565.44873365,
       461.6404661 , 449.82713468, 422.41864012, 456.60610254,
       600.10957705, 451.86032555, 615.85144117, 512.40209335,
       501.69003525, 517.56160627, 572.58037994, 552.48535466,
       357.92687296, 464.68184546, 481.83627598, 533.77655916,
       256.52220131, 505.41213804, 521.26909837, 314.12711628,
       503.61844899, 390.20244049, 473.36318979, 432.67105172,
       540.64529118, 590.3762177 , 761.28550379, 557.19

### Спрогнозуйте значення річних витрат для тестових даних.

In [22]:
mse = mean_squared_error(y_test, y_pred_poly)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_poly)

# Виведення результатів
print(f"Середня квадратична помилка (MSE): {mse}")
print(f"Корінь середньоквадратичної помилки (RMSE): {rmse}")
print(f"Коефіцієнт детермінації (R^2): {r2}")

Середня квадратична помилка (MSE): 85.34745505512613
Корінь середньоквадратичної помилки (RMSE): 9.238368636026934
Коефіцієнт детермінації (R^2): 0.9882421824247083


## Опорна векторна регресія.

### Промасштабуйте дані.

In [ ]:
scaler_X = StandardScaler()
scaler_y = StandardScaler()

### Створіть та натренуйте модель.

In [17]:
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
svr_model = make_pipeline(StandardScaler(), SVR(kernel='rbf'))
svr_model.fit(X_train, y_train)
y_pred_svm = svr_model.predict(X_test)
y_pred_svm

array([497.20064859, 486.41307779, 475.63836043, 537.57163018,
       529.62562868, 521.98785322, 516.10038676, 518.4457641 ,
       498.14901813, 518.15908531, 458.19152829, 495.04471707,
       513.0931025 , 474.30509748, 509.48662762, 519.31662938,
       527.149468  , 498.2408295 , 520.88468524, 514.08326811,
       493.98315339, 524.30278308, 491.86108211, 488.09575597,
       522.99959204, 482.4778982 , 510.9065245 , 481.24478752,
       509.45655708, 487.90882008, 522.7271829 , 515.29345227,
       499.86193561, 517.99346295, 498.65097934, 522.23915716,
       492.61398199, 475.73845421, 475.79720748, 480.17084059,
       519.44931907, 489.06496618, 532.01715031, 505.63046382,
       502.63100744, 501.08738651, 508.12574586, 516.25613927,
       482.65923986, 484.8331726 , 492.37585326, 518.47231352,
       486.29076277, 504.67660533, 507.78609895, 479.99203681,
       499.56969758, 480.03544609, 484.46950447, 474.0174349 ,
       510.91622033, 533.03967988, 502.60588576, 514.29

### Спрогнозуйте значення річних витрат для тестових даних.

In [18]:
mse = mean_squared_error(y_test, y_pred_svm)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_svm)

# Виведення результатів
print(f"Середня квадратична помилка (MSE): {mse}")
print(f"Корінь середньоквадратичної помилки (RMSE): {rmse}")
print(f"Коефіцієнт детермінації (R^2): {r2}")

Середня квадратична помилка (MSE): 4951.809909187463
Корінь середньоквадратичної помилки (RMSE): 70.36909768632438
Коефіцієнт детермінації (R^2): 0.31781823439091295


## Регресія з деревами прийняття рішень.

### Створіть та натренуйте модель.

In [19]:
from sklearn.tree import DecisionTreeRegressor
decision_tree_regressor = DecisionTreeRegressor(random_state=101)
decision_tree_regressor.fit(X_train, y_train)
y_pred_tree = decision_tree_regressor.predict(X_test)
y_pred_tree

array([436.51560573, 392.28524425, 424.67528101, 587.95105397,
       627.60331871, 536.42310453, 596.43017262, 725.58481406,
       468.44573723, 573.30622226, 352.55010816, 421.32663126,
       570.45172591, 388.94054879, 725.58481406, 570.63009809,
       604.84131882, 503.21739312, 528.4193297 , 557.60826205,
       443.96562681, 604.33484007, 475.0716299 , 514.33655827,
       576.02524413, 468.44573723, 503.21739312, 357.85798361,
       503.21739312, 463.59141803, 630.42276323, 626.01867266,
       444.58216498, 551.0230017 , 468.6684656 , 550.04758058,
       438.30370785, 482.83098586, 456.46951007, 444.58216498,
       584.21831349, 424.67528101, 613.59932337, 529.23009012,
       546.55666686, 530.36246889, 533.51493526, 530.36246889,
       378.33090691, 478.71935687, 508.73574095, 518.78648309,
       298.76200786, 506.42385997, 576.8025474 , 298.76200786,
       492.94505307, 422.36873661, 463.4849954 , 436.72055586,
       503.21739312, 581.30893288, 637.10244792, 547.12

### Спрогнозуйте значення річних витрат для тестових даних.

In [20]:
mse = mean_squared_error(y_test, y_pred_tree)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_tree)

# Виведення результатів
print(f"Середня квадратична помилка (MSE): {mse}")
print(f"Корінь середньоквадратичної помилки (RMSE): {rmse}")
print(f"Коефіцієнт детермінації (R^2): {r2}")

Середня квадратична помилка (MSE): 968.662997118106
Корінь середньоквадратичної помилки (RMSE): 31.123351315661782
Коефіцієнт детермінації (R^2): 0.8665529885490596


In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Список документів
documents = [
    "Машинне навчання з використанням алгоритмів",
    "Алгоритм машинного навчання для обробки даних",
    "Моделі машинного навчання для класифікації",
    "Нейронні мережі для класифікації зображень"
]

# Створюємо об'єкт TfidfVectorizer
vectorizer = TfidfVectorizer()

# Підраховуємо TF-IDF для кожного слова в кожному документі
tfidf_matrix = vectorizer.fit_transform(documents)

# Обчислюємо косинусну подібність між усіма документами
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Виводимо косинусну подібність між документами
print(cosine_sim)


[[1.         0.10478614 0.12621201 0.        ]
 [0.10478614 1.         0.38998174 0.09636454]
 [0.12621201 0.38998174 1.         0.29315593]
 [0.         0.09636454 0.29315593 1.        ]]
